[package]
name = "syntax_codegen"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
tree-sitter = "0.19"
tree-sitter-typescript = "0.19"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1"
quote = "1.0.9"
proc-macro2 = "1"
xshell = "0.1"
indexmap = {version = "1", features = ["serde-1"] }